import Layout from '@/src/components/layout/Layout'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Layout',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return <Layout children={children} />
}
